/* File: _dpropackmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Thu Dec 13 17:05:42 2012
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_dpropack_error;
static PyObject *_dpropack_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef signed char signed_char;
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef float(*cb_daprod_in___user__routines_typedef)(string,int *,int *,double *,double *,double *,int *,int);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
  fprintf(stderr,"_dpropack.error is related to ");\
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
    if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
    if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
      goto capi_fail;\
  }

#define pyobj_from_string1size(v,len) (PyString_FromStringAndSize((char *)v, len))
#define pyobj_from_int1(v) (PyInt_FromLong(v))
#define MEMCOPY(to,from,n)\
    do { FAILNULL(to); FAILNULL(from); (void)memcpy(to,from,n); } while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define SWAP(a,b,t) {\
  t *c;\
  c = a;\
  a = b;\
  b = c;}

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(_dpropack_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _dpropack_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _dpropack_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (arr->descr->elsize)*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,arr->data,*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _dpropack_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
  PyObject *tmp = NULL;
  PyObject *tmp_fun = NULL;
  int tot,opt,ext,siz,i,di=0;
  CFUNCSMESS("create_cb_arglist\n");
  tot=opt=ext=siz=0;
  /* Get the total number of arguments */
  if (PyFunction_Check(fun))
    tmp_fun = fun;
  else {
    di = 1;
    if (PyObject_HasAttrString(fun,"im_func")) {
      tmp_fun = PyObject_GetAttrString(fun,"im_func");
    }
    else if (PyObject_HasAttrString(fun,"__call__")) {
      tmp = PyObject_GetAttrString(fun,"__call__");
      if (PyObject_HasAttrString(tmp,"im_func"))
        tmp_fun = PyObject_GetAttrString(tmp,"im_func");
      else {
        tmp_fun = fun; /* built-in function */
        tot = maxnofargs;
        if (xa != NULL)
          tot += PyTuple_Size((PyObject *)xa);
      }
      Py_XDECREF(tmp);
    }
    else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        tot += PyTuple_Size((PyObject *)xa);
      tmp_fun = fun;
    }
    else if (F2PyCapsule_Check(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
      if(ext>0) {
        fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
        goto capi_fail;
      }
      tmp_fun = fun;
    }
  }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__code__")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_code")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
      tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
    Py_XDECREF(tmp);
  }
  /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__defaults__"))
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_defaults"))
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
      opt = PyTuple_Size(tmp);
    Py_XDECREF(tmp);
  /* Get the number of extra arguments */
  if (xa != NULL)
    ext = PyTuple_Size((PyObject *)xa);
  /* Calculate the size of call-backs argument list */
  siz = MIN(maxnofargs+ext,tot);
  *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
  fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
  if (siz<tot-opt) {
    fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
    goto capi_fail;
  }
  /* Initialize argument list */
  *args = (PyTupleObject *)PyTuple_New(siz);
  for (i=0;i<*nofargs;i++) {
    Py_INCREF(Py_None);
    PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
  }
  if (xa != NULL)
    for (i=(*nofargs);i<siz;i++) {
      tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
      Py_INCREF(tmp);
      PyTuple_SET_ITEM(*args,i,tmp);
    }
  CFUNCSMESS("create_cb_arglist-end\n");
  return 1;
capi_fail:
  if ((PyErr_Occurred())==NULL)
    PyErr_SetString(_dpropack_error,errmess);
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(dlansvd,DLANSVD)(string,string,int*,int*,int*,int*,cb_daprod_in___user__routines_typedef,double*,int*,double*,double*,double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,double*,int*,size_t,size_t);
extern void F_FUNC_US(dlansvd_irl,DLANSVD_IRL)(string,string,string,int*,int*,int*,int*,int*,int*,cb_daprod_in___user__routines_typedef,double*,int*,double*,double*,double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,double*,int*,size_t,size_t,size_t);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/*********************** cb_daprod_in___user__routines ***********************/
PyObject *cb_daprod_in___user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_daprod_in___user__routines_args_capi = NULL;
int cb_daprod_in___user__routines_nofargs = 0;
jmp_buf cb_daprod_in___user__routines_jmpbuf;
/*typedef float(*cb_daprod_in___user__routines_typedef)(string,int *,int *,double *,double *,double *,int *,int);*/
static float cb_daprod_in___user__routines (string transa,int *m_cb_capi,int *n_cb_capi,double *x,double *y,double *dparm,int *iparm,int transa_cb_len) {
  PyTupleObject *capi_arglist = cb_daprod_in___user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  float return_value;
  int m=(*m_cb_capi);
  int n=(*n_cb_capi);
  npy_intp dparm_Dims[1] = {-1};
  npy_intp iparm_Dims[1] = {-1};
  npy_intp y_Dims[1] = {-1};
  npy_intp x_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_daprod_in___user__routines (maxnofargs=7(-0))\n");
  CFUNCSMESSPY("cb:cb_daprod_in___user__routines_capi=",cb_daprod_in___user__routines_capi);
  if (cb_daprod_in___user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_daprod_in___user__routines_capi = PyObject_GetAttrString(_dpropack_module,"daprod");
  }
  if (cb_daprod_in___user__routines_capi==NULL) {
    PyErr_SetString(_dpropack_error,"cb: Callback daprod not defined (as an argument or module _dpropack attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_daprod_in___user__routines_capi)) {
  cb_daprod_in___user__routines_typedef cb_daprod_in___user__routines_cptr;
  cb_daprod_in___user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_daprod_in___user__routines_capi);
  return_value=(*cb_daprod_in___user__routines_cptr)(transa,m_cb_capi,n_cb_capi,x,y,dparm,iparm,transa_cb_len);
    return return_value;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(_dpropack_module,"daprod_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(_dpropack_error,"Failed to convert _dpropack.daprod_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(_dpropack_error,"Callback daprod argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  dparm_Dims[0]=0;
  iparm_Dims[0]=0;
  y_Dims[0]=max(m,n);
  x_Dims[0]=max(m,n);
/*pyobjfrom*/
  if (cb_daprod_in___user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_string1size(transa,transa_cb_len)))
      goto capi_fail;
  if (cb_daprod_in___user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(m)))
      goto capi_fail;
  if (cb_daprod_in___user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(n)))
      goto capi_fail;
  if (cb_daprod_in___user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_daprod_in___user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,y_Dims,NPY_DOUBLE,NULL,(char*)y,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_daprod_in___user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,dparm_Dims,NPY_DOUBLE,NULL,(char*)dparm,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_daprod_in___user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,iparm_Dims,NPY_INT,NULL,(char*)iparm,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function daprod.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_daprod_in___user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,&return_value,float,"float_from_pyobj failed in converting return_value of call-back function cb_daprod_in___user__routines to C float\n");
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,x_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(x,rv_cb_arr->data,PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,y_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(y,rv_cb_arr->data,PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_daprod_in___user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_daprod_in___user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_daprod_in___user__routines_jmpbuf,-1);
capi_return_pt:
  ;
  return return_value;
}
/******************** end of cb_daprod_in___user__routines ********************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** dlansvd **********************************/
static char doc_f2py_rout__dpropack_dlansvd[] = "\
Function signature:\n\
  u,sigma,bnd,v,work,iwork,info = dlansvd(jobu,jobv,m,n,k,aprod,u,v,tolin,work,iwork,doption,ioption,dparm,iparm,[kmax,ldu,ldv,lwork,liwork,aprod_extra_args])\n\
Required arguments:\n"
"  jobu : input string(len=1)\n"
"  jobv : input string(len=1)\n"
"  m : input int\n"
"  n : input int\n"
"  k : input int\n"
"  aprod : call-back function => daprod\n"
"  u : input rank-2 array('d') with bounds (ldu,kmax + 1)\n"
"  v : input rank-2 array('d') with bounds (ldv,kmax)\n"
"  tolin : input float\n"
"  work : input rank-1 array('d') with bounds (lwork)\n"
"  iwork : input rank-1 array('i') with bounds (liwork)\n"
"  doption : input rank-1 array('d') with bounds (3)\n"
"  ioption : input rank-1 array('i') with bounds (2)\n"
"  dparm : input rank-1 array('d') with bounds (*)\n"
"  iparm : input rank-1 array('i') with bounds (*)\n"
"Optional arguments:\n"
"  kmax := (shape(u,1)-1) input int\n"
"  aprod_extra_args := () input tuple\n"
"  ldu := shape(u,0) input int\n"
"  ldv := shape(v,0) input int\n"
"  lwork := len(work) input int\n"
"  liwork := len(iwork) input int\n"
"Return objects:\n"
"  u : rank-2 array('d') with bounds (ldu,kmax + 1)\n"
"  sigma : rank-1 array('d') with bounds (k)\n"
"  bnd : rank-1 array('d') with bounds (k)\n"
"  v : rank-2 array('d') with bounds (ldv,kmax)\n"
"  work : rank-1 array('d') with bounds (lwork)\n"
"  iwork : rank-1 array('i') with bounds (liwork)\n"
"  info : int\n"
"Call-back functions:\n"
"  def daprod(transa,m,n,x,y,dparm,iparm): return daprod,x,y\n\
  Required arguments:\n"
"    transa : input string(len=1)\n"
"    m : input int\n"
"    n : input int\n"
"    x : input rank-1 array('d') with bounds (max(m,n))\n"
"    y : input rank-1 array('d') with bounds (max(m,n))\n"
"    dparm : input rank-1 array('d') with bounds (*)\n"
"    iparm : input rank-1 array('i') with bounds (*)\n"
"  Return objects:\n"
"    daprod : float\n"
"    x : rank-1 array('d') with bounds (max(m,n))\n"
"    y : rank-1 array('d') with bounds (max(m,n))";
/* extern void F_FUNC(dlansvd,DLANSVD)(string,string,int*,int*,int*,int*,cb_daprod_in___user__routines_typedef,double*,int*,double*,double*,double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,double*,int*,size_t,size_t); */
static PyObject *f2py_rout__dpropack_dlansvd(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,int*,int*,int*,int*,cb_daprod_in___user__routines_typedef,double*,int*,double*,double*,double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,double*,int*,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string jobu = NULL;
  int slen(jobu);
  PyObject *jobu_capi = Py_None;
  string jobv = NULL;
  int slen(jobv);
  PyObject *jobv_capi = Py_None;
  int m = 0;
  PyObject *m_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int k = 0;
  PyObject *k_capi = Py_None;
  int kmax = 0;
  PyObject *kmax_capi = Py_None;
  PyObject *aprod_capi = Py_None;
  PyTupleObject *aprod_xa_capi = NULL;
  PyTupleObject *aprod_args_capi = NULL;
  int aprod_nofargs_capi = 0;
  cb_daprod_in___user__routines_typedef aprod_cptr;
  double *u = NULL;
  npy_intp u_Dims[2] = {-1, -1};
  const int u_Rank = 2;
  PyArrayObject *capi_u_tmp = NULL;
  int capi_u_intent = 0;
  PyObject *u_capi = Py_None;
  int ldu = 0;
  PyObject *ldu_capi = Py_None;
  double *sigma = NULL;
  npy_intp sigma_Dims[1] = {-1};
  const int sigma_Rank = 1;
  PyArrayObject *capi_sigma_tmp = NULL;
  int capi_sigma_intent = 0;
  double *bnd = NULL;
  npy_intp bnd_Dims[1] = {-1};
  const int bnd_Rank = 1;
  PyArrayObject *capi_bnd_tmp = NULL;
  int capi_bnd_intent = 0;
  double *v = NULL;
  npy_intp v_Dims[2] = {-1, -1};
  const int v_Rank = 2;
  PyArrayObject *capi_v_tmp = NULL;
  int capi_v_intent = 0;
  PyObject *v_capi = Py_None;
  int ldv = 0;
  PyObject *ldv_capi = Py_None;
  double tolin = 0;
  PyObject *tolin_capi = Py_None;
  double *work = NULL;
  npy_intp work_Dims[1] = {-1};
  const int work_Rank = 1;
  PyArrayObject *capi_work_tmp = NULL;
  int capi_work_intent = 0;
  PyObject *work_capi = Py_None;
  int lwork = 0;
  PyObject *lwork_capi = Py_None;
  int *iwork = NULL;
  npy_intp iwork_Dims[1] = {-1};
  const int iwork_Rank = 1;
  PyArrayObject *capi_iwork_tmp = NULL;
  int capi_iwork_intent = 0;
  PyObject *iwork_capi = Py_None;
  int liwork = 0;
  PyObject *liwork_capi = Py_None;
  double *doption = NULL;
  npy_intp doption_Dims[1] = {-1};
  const int doption_Rank = 1;
  PyArrayObject *capi_doption_tmp = NULL;
  int capi_doption_intent = 0;
  PyObject *doption_capi = Py_None;
  int *ioption = NULL;
  npy_intp ioption_Dims[1] = {-1};
  const int ioption_Rank = 1;
  PyArrayObject *capi_ioption_tmp = NULL;
  int capi_ioption_intent = 0;
  PyObject *ioption_capi = Py_None;
  int info = 0;
  double *dparm = NULL;
  npy_intp dparm_Dims[1] = {-1};
  const int dparm_Rank = 1;
  PyArrayObject *capi_dparm_tmp = NULL;
  int capi_dparm_intent = 0;
  PyObject *dparm_capi = Py_None;
  int *iparm = NULL;
  npy_intp iparm_Dims[1] = {-1};
  const int iparm_Rank = 1;
  PyArrayObject *capi_iparm_tmp = NULL;
  int capi_iparm_intent = 0;
  PyObject *iparm_capi = Py_None;
  static char *capi_kwlist[] = {"jobu","jobv","m","n","k","aprod","u","v","tolin","work","iwork","doption","ioption","dparm","iparm","kmax","ldu","ldv","lwork","liwork","aprod_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOO|OOOOOO!:_dpropack.dlansvd",\
    capi_kwlist,&jobu_capi,&jobv_capi,&m_capi,&n_capi,&k_capi,&aprod_capi,&u_capi,&v_capi,&tolin_capi,&work_capi,&iwork_capi,&doption_capi,&ioption_capi,&dparm_capi,&iparm_capi,&kmax_capi,&ldu_capi,&ldv_capi,&lwork_capi,&liwork_capi,&PyTuple_Type,&aprod_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ioption */
  ioption_Dims[0]=2;
  capi_ioption_intent |= F2PY_INTENT_IN;
  capi_ioption_tmp = array_from_pyobj(NPY_INT,ioption_Dims,ioption_Rank,capi_ioption_intent,ioption_capi);
  if (capi_ioption_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 13rd argument `ioption' of _dpropack.dlansvd to C/Fortran array" );
  } else {
    ioption = (int *)(capi_ioption_tmp->data);

  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"_dpropack.dlansvd() 4th argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable u */
  ;
  capi_u_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_u_tmp = array_from_pyobj(NPY_DOUBLE,u_Dims,u_Rank,capi_u_intent,u_capi);
  if (capi_u_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 7th argument `u' of _dpropack.dlansvd to C/Fortran array" );
  } else {
    u = (double *)(capi_u_tmp->data);

  /* Processing variable iparm */
  ;
  capi_iparm_intent |= F2PY_INTENT_IN;
  capi_iparm_tmp = array_from_pyobj(NPY_INT,iparm_Dims,iparm_Rank,capi_iparm_intent,iparm_capi);
  if (capi_iparm_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 15th argument `iparm' of _dpropack.dlansvd to C/Fortran array" );
  } else {
    iparm = (int *)(capi_iparm_tmp->data);

  /* Processing variable jobv */
  slen(jobv) = 1;
  f2py_success = string_from_pyobj(&jobv,&slen(jobv),"",jobv_capi,"string_from_pyobj failed in converting 2nd argument `jobv' of _dpropack.dlansvd to C string");
  if (f2py_success) {
  /* Processing variable jobu */
  slen(jobu) = 1;
  f2py_success = string_from_pyobj(&jobu,&slen(jobu),"",jobu_capi,"string_from_pyobj failed in converting 1st argument `jobu' of _dpropack.dlansvd to C string");
  if (f2py_success) {
  /* Processing variable tolin */
    f2py_success = double_from_pyobj(&tolin,tolin_capi,"_dpropack.dlansvd() 9th argument (tolin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable aprod */
if(F2PyCapsule_Check(aprod_capi)) {
  aprod_cptr = F2PyCapsule_AsVoidPtr(aprod_capi);
} else {
  aprod_cptr = cb_daprod_in___user__routines;
}

  aprod_nofargs_capi = cb_daprod_in___user__routines_nofargs;
  if (create_cb_arglist(aprod_capi,aprod_xa_capi,7,0,&cb_daprod_in___user__routines_nofargs,&aprod_args_capi,"failed in processing argument list for call-back aprod.")) {
    jmp_buf aprod_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `aprod`.\n");
    SWAP(aprod_capi,cb_daprod_in___user__routines_capi,PyObject);
    SWAP(aprod_args_capi,cb_daprod_in___user__routines_args_capi,PyTupleObject);
    memcpy(&aprod_jmpbuf,&cb_daprod_in___user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable iwork */
  ;
  capi_iwork_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_iwork_tmp = array_from_pyobj(NPY_INT,iwork_Dims,iwork_Rank,capi_iwork_intent,iwork_capi);
  if (capi_iwork_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 11st argument `iwork' of _dpropack.dlansvd to C/Fortran array" );
  } else {
    iwork = (int *)(capi_iwork_tmp->data);

  /* Processing variable info */
  /* Processing variable k */
    f2py_success = int_from_pyobj(&k,k_capi,"_dpropack.dlansvd() 5th argument (k) can't be converted to int");
  if (f2py_success) {
  /* Processing variable work */
  ;
  capi_work_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_work_tmp = array_from_pyobj(NPY_DOUBLE,work_Dims,work_Rank,capi_work_intent,work_capi);
  if (capi_work_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 10th argument `work' of _dpropack.dlansvd to C/Fortran array" );
  } else {
    work = (double *)(capi_work_tmp->data);

  /* Processing variable m */
    f2py_success = int_from_pyobj(&m,m_capi,"_dpropack.dlansvd() 3rd argument (m) can't be converted to int");
  if (f2py_success) {
  /* Processing variable dparm */
  ;
  capi_dparm_intent |= F2PY_INTENT_IN;
  capi_dparm_tmp = array_from_pyobj(NPY_DOUBLE,dparm_Dims,dparm_Rank,capi_dparm_intent,dparm_capi);
  if (capi_dparm_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 14th argument `dparm' of _dpropack.dlansvd to C/Fortran array" );
  } else {
    dparm = (double *)(capi_dparm_tmp->data);

  /* Processing variable doption */
  doption_Dims[0]=3;
  capi_doption_intent |= F2PY_INTENT_IN;
  capi_doption_tmp = array_from_pyobj(NPY_DOUBLE,doption_Dims,doption_Rank,capi_doption_intent,doption_capi);
  if (capi_doption_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 12nd argument `doption' of _dpropack.dlansvd to C/Fortran array" );
  } else {
    doption = (double *)(capi_doption_tmp->data);

  /* Processing variable ldu */
  if (ldu_capi == Py_None) ldu = shape(u,0); else
    f2py_success = int_from_pyobj(&ldu,ldu_capi,"_dpropack.dlansvd() 2nd keyword (ldu) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u,0)==ldu,"shape(u,0)==ldu","2nd keyword ldu","dlansvd:ldu=%d",ldu) {
  /* Processing variable lwork */
  if (lwork_capi == Py_None) lwork = len(work); else
    f2py_success = int_from_pyobj(&lwork,lwork_capi,"_dpropack.dlansvd() 4th keyword (lwork) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(work)>=lwork,"len(work)>=lwork","4th keyword lwork","dlansvd:lwork=%d",lwork) {
  /* Processing variable bnd */
  bnd_Dims[0]=k;
  capi_bnd_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_bnd_tmp = array_from_pyobj(NPY_DOUBLE,bnd_Dims,bnd_Rank,capi_bnd_intent,Py_None);
  if (capi_bnd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting hidden `bnd' of _dpropack.dlansvd to C/Fortran array" );
  } else {
    bnd = (double *)(capi_bnd_tmp->data);

  /* Processing variable liwork */
  if (liwork_capi == Py_None) liwork = len(iwork); else
    f2py_success = int_from_pyobj(&liwork,liwork_capi,"_dpropack.dlansvd() 5th keyword (liwork) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(iwork)>=liwork,"len(iwork)>=liwork","5th keyword liwork","dlansvd:liwork=%d",liwork) {
  /* Processing variable kmax */
  if (kmax_capi == Py_None) kmax = (shape(u,1)-1); else
    f2py_success = int_from_pyobj(&kmax,kmax_capi,"_dpropack.dlansvd() 1st keyword (kmax) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR((shape(u,1)-1)==kmax,"(shape(u,1)-1)==kmax","1st keyword kmax","dlansvd:kmax=%d",kmax) {
  /* Processing variable sigma */
  sigma_Dims[0]=k;
  capi_sigma_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_sigma_tmp = array_from_pyobj(NPY_DOUBLE,sigma_Dims,sigma_Rank,capi_sigma_intent,Py_None);
  if (capi_sigma_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting hidden `sigma' of _dpropack.dlansvd to C/Fortran array" );
  } else {
    sigma = (double *)(capi_sigma_tmp->data);

  /* Processing variable v */
  v_Dims[1]=kmax;
  capi_v_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_v_tmp = array_from_pyobj(NPY_DOUBLE,v_Dims,v_Rank,capi_v_intent,v_capi);
  if (capi_v_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 8th argument `v' of _dpropack.dlansvd to C/Fortran array" );
  } else {
    v = (double *)(capi_v_tmp->data);

  /* Processing variable ldv */
  if (ldv_capi == Py_None) ldv = shape(v,0); else
    f2py_success = int_from_pyobj(&ldv,ldv_capi,"_dpropack.dlansvd() 3rd keyword (ldv) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(v,0)==ldv,"shape(v,0)==ldv","3rd keyword ldv","dlansvd:ldv=%d",ldv) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_daprod_in___user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(jobu,jobv,&m,&n,&k,&kmax,aprod_cptr,u,&ldu,sigma,bnd,v,&ldv,&tolin,work,&lwork,iwork,&liwork,doption,ioption,&info,dparm,iparm,slen(jobu),slen(jobv));
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNNNNi",capi_u_tmp,capi_sigma_tmp,capi_bnd_tmp,capi_v_tmp,capi_work_tmp,capi_iwork_tmp,info);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(v,0)==ldv)*/
  } /*if (f2py_success) of ldv*/
  /* End of cleaning variable ldv */
  }  /*if (capi_v_tmp == NULL) ... else of v*/
  /* End of cleaning variable v */
  }  /*if (capi_sigma_tmp == NULL) ... else of sigma*/
  /* End of cleaning variable sigma */
  } /*CHECKSCALAR((shape(u,1)-1)==kmax)*/
  } /*if (f2py_success) of kmax*/
  /* End of cleaning variable kmax */
  } /*CHECKSCALAR(len(iwork)>=liwork)*/
  } /*if (f2py_success) of liwork*/
  /* End of cleaning variable liwork */
  }  /*if (capi_bnd_tmp == NULL) ... else of bnd*/
  /* End of cleaning variable bnd */
  } /*CHECKSCALAR(len(work)>=lwork)*/
  } /*if (f2py_success) of lwork*/
  /* End of cleaning variable lwork */
  } /*CHECKSCALAR(shape(u,0)==ldu)*/
  } /*if (f2py_success) of ldu*/
  /* End of cleaning variable ldu */
  if((PyObject *)capi_doption_tmp!=doption_capi) {
    Py_XDECREF(capi_doption_tmp); }
  }  /*if (capi_doption_tmp == NULL) ... else of doption*/
  /* End of cleaning variable doption */
  if((PyObject *)capi_dparm_tmp!=dparm_capi) {
    Py_XDECREF(capi_dparm_tmp); }
  }  /*if (capi_dparm_tmp == NULL) ... else of dparm*/
  /* End of cleaning variable dparm */
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  }  /*if (capi_work_tmp == NULL) ... else of work*/
  /* End of cleaning variable work */
  } /*if (f2py_success) of k*/
  /* End of cleaning variable k */
  /* End of cleaning variable info */
  }  /*if (capi_iwork_tmp == NULL) ... else of iwork*/
  /* End of cleaning variable iwork */
    CFUNCSMESS("Restoring jmpbuf for `aprod`.\n");
    cb_daprod_in___user__routines_capi = aprod_capi;
    Py_DECREF(cb_daprod_in___user__routines_args_capi);
    cb_daprod_in___user__routines_args_capi = aprod_args_capi;
    cb_daprod_in___user__routines_nofargs = aprod_nofargs_capi;
    memcpy(&cb_daprod_in___user__routines_jmpbuf,&aprod_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable aprod */
  } /*if (f2py_success) of tolin*/
  /* End of cleaning variable tolin */
    STRINGFREE(jobu);
  }  /*if (f2py_success) of jobu*/
  /* End of cleaning variable jobu */
    STRINGFREE(jobv);
  }  /*if (f2py_success) of jobv*/
  /* End of cleaning variable jobv */
  if((PyObject *)capi_iparm_tmp!=iparm_capi) {
    Py_XDECREF(capi_iparm_tmp); }
  }  /*if (capi_iparm_tmp == NULL) ... else of iparm*/
  /* End of cleaning variable iparm */
  }  /*if (capi_u_tmp == NULL) ... else of u*/
  /* End of cleaning variable u */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_ioption_tmp!=ioption_capi) {
    Py_XDECREF(capi_ioption_tmp); }
  }  /*if (capi_ioption_tmp == NULL) ... else of ioption*/
  /* End of cleaning variable ioption */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of dlansvd *******************************/

/******************************** dlansvd_irl ********************************/
static char doc_f2py_rout__dpropack_dlansvd_irl[] = "\
Function signature:\n\
  dlansvd_irl(which,jobu,jobv,m,n,dim,p,neig,maxiter,aprod,u,sigma,bnd,v,tolin,work,iwork,doption,ioption,info,dparm,iparm,[ldu,ldv,lwork,liwork,aprod_extra_args])\n\
Required arguments:\n"
"  which : input string(len=1)\n"
"  jobu : input string(len=1)\n"
"  jobv : input string(len=1)\n"
"  m : input int\n"
"  n : input int\n"
"  dim : input int\n"
"  p : input int\n"
"  neig : input int\n"
"  maxiter : input int\n"
"  aprod : call-back function => daprod\n"
"  u : input rank-2 array('d') with bounds (ldu,*)\n"
"  sigma : input rank-1 array('d') with bounds (*)\n"
"  bnd : input rank-1 array('d') with bounds (*)\n"
"  v : input rank-2 array('d') with bounds (ldv,*)\n"
"  tolin : input float\n"
"  work : input rank-1 array('d') with bounds (lwork)\n"
"  iwork : input rank-1 array('i') with bounds (liwork)\n"
"  doption : input rank-1 array('d') with bounds (*)\n"
"  ioption : input rank-1 array('i') with bounds (*)\n"
"  info : input int\n"
"  dparm : input rank-1 array('d') with bounds (*)\n"
"  iparm : input rank-1 array('i') with bounds (*)\n"
"Optional arguments:\n"
"  aprod_extra_args := () input tuple\n"
"  ldu := shape(u,0) input int\n"
"  ldv := shape(v,0) input int\n"
"  lwork := len(work) input int\n"
"  liwork := len(iwork) input int\n"
"Call-back functions:\n"
"  def daprod(transa,m,n,x,y,dparm,iparm): return daprod,x,y\n\
  Required arguments:\n"
"    transa : input string(len=1)\n"
"    m : input int\n"
"    n : input int\n"
"    x : input rank-1 array('d') with bounds (max(m,n))\n"
"    y : input rank-1 array('d') with bounds (max(m,n))\n"
"    dparm : input rank-1 array('d') with bounds (*)\n"
"    iparm : input rank-1 array('i') with bounds (*)\n"
"  Return objects:\n"
"    daprod : float\n"
"    x : rank-1 array('d') with bounds (max(m,n))\n"
"    y : rank-1 array('d') with bounds (max(m,n))";
/* extern void F_FUNC_US(dlansvd_irl,DLANSVD_IRL)(string,string,string,int*,int*,int*,int*,int*,int*,cb_daprod_in___user__routines_typedef,double*,int*,double*,double*,double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,double*,int*,size_t,size_t,size_t); */
static PyObject *f2py_rout__dpropack_dlansvd_irl(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,string,int*,int*,int*,int*,int*,int*,cb_daprod_in___user__routines_typedef,double*,int*,double*,double*,double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,double*,int*,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string which = NULL;
  int slen(which);
  PyObject *which_capi = Py_None;
  string jobu = NULL;
  int slen(jobu);
  PyObject *jobu_capi = Py_None;
  string jobv = NULL;
  int slen(jobv);
  PyObject *jobv_capi = Py_None;
  int m = 0;
  PyObject *m_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int dim = 0;
  PyObject *dim_capi = Py_None;
  int p = 0;
  PyObject *p_capi = Py_None;
  int neig = 0;
  PyObject *neig_capi = Py_None;
  int maxiter = 0;
  PyObject *maxiter_capi = Py_None;
  PyObject *aprod_capi = Py_None;
  PyTupleObject *aprod_xa_capi = NULL;
  PyTupleObject *aprod_args_capi = NULL;
  int aprod_nofargs_capi = 0;
  cb_daprod_in___user__routines_typedef aprod_cptr;
  double *u = NULL;
  npy_intp u_Dims[2] = {-1, -1};
  const int u_Rank = 2;
  PyArrayObject *capi_u_tmp = NULL;
  int capi_u_intent = 0;
  PyObject *u_capi = Py_None;
  int ldu = 0;
  PyObject *ldu_capi = Py_None;
  double *sigma = NULL;
  npy_intp sigma_Dims[1] = {-1};
  const int sigma_Rank = 1;
  PyArrayObject *capi_sigma_tmp = NULL;
  int capi_sigma_intent = 0;
  PyObject *sigma_capi = Py_None;
  double *bnd = NULL;
  npy_intp bnd_Dims[1] = {-1};
  const int bnd_Rank = 1;
  PyArrayObject *capi_bnd_tmp = NULL;
  int capi_bnd_intent = 0;
  PyObject *bnd_capi = Py_None;
  double *v = NULL;
  npy_intp v_Dims[2] = {-1, -1};
  const int v_Rank = 2;
  PyArrayObject *capi_v_tmp = NULL;
  int capi_v_intent = 0;
  PyObject *v_capi = Py_None;
  int ldv = 0;
  PyObject *ldv_capi = Py_None;
  double tolin = 0;
  PyObject *tolin_capi = Py_None;
  double *work = NULL;
  npy_intp work_Dims[1] = {-1};
  const int work_Rank = 1;
  PyArrayObject *capi_work_tmp = NULL;
  int capi_work_intent = 0;
  PyObject *work_capi = Py_None;
  int lwork = 0;
  PyObject *lwork_capi = Py_None;
  int *iwork = NULL;
  npy_intp iwork_Dims[1] = {-1};
  const int iwork_Rank = 1;
  PyArrayObject *capi_iwork_tmp = NULL;
  int capi_iwork_intent = 0;
  PyObject *iwork_capi = Py_None;
  int liwork = 0;
  PyObject *liwork_capi = Py_None;
  double *doption = NULL;
  npy_intp doption_Dims[1] = {-1};
  const int doption_Rank = 1;
  PyArrayObject *capi_doption_tmp = NULL;
  int capi_doption_intent = 0;
  PyObject *doption_capi = Py_None;
  int *ioption = NULL;
  npy_intp ioption_Dims[1] = {-1};
  const int ioption_Rank = 1;
  PyArrayObject *capi_ioption_tmp = NULL;
  int capi_ioption_intent = 0;
  PyObject *ioption_capi = Py_None;
  int info = 0;
  PyObject *info_capi = Py_None;
  double *dparm = NULL;
  npy_intp dparm_Dims[1] = {-1};
  const int dparm_Rank = 1;
  PyArrayObject *capi_dparm_tmp = NULL;
  int capi_dparm_intent = 0;
  PyObject *dparm_capi = Py_None;
  int *iparm = NULL;
  npy_intp iparm_Dims[1] = {-1};
  const int iparm_Rank = 1;
  PyArrayObject *capi_iparm_tmp = NULL;
  int capi_iparm_intent = 0;
  PyObject *iparm_capi = Py_None;
  static char *capi_kwlist[] = {"which","jobu","jobv","m","n","dim","p","neig","maxiter","aprod","u","sigma","bnd","v","tolin","work","iwork","doption","ioption","info","dparm","iparm","ldu","ldv","lwork","liwork","aprod_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOO|OOOOO!:_dpropack.dlansvd_irl",\
    capi_kwlist,&which_capi,&jobu_capi,&jobv_capi,&m_capi,&n_capi,&dim_capi,&p_capi,&neig_capi,&maxiter_capi,&aprod_capi,&u_capi,&sigma_capi,&bnd_capi,&v_capi,&tolin_capi,&work_capi,&iwork_capi,&doption_capi,&ioption_capi,&info_capi,&dparm_capi,&iparm_capi,&ldu_capi,&ldv_capi,&lwork_capi,&liwork_capi,&PyTuple_Type,&aprod_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable v */
  ;
  capi_v_intent |= F2PY_INTENT_IN;
  capi_v_tmp = array_from_pyobj(NPY_DOUBLE,v_Dims,v_Rank,capi_v_intent,v_capi);
  if (capi_v_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 14th argument `v' of _dpropack.dlansvd_irl to C/Fortran array" );
  } else {
    v = (double *)(capi_v_tmp->data);

  /* Processing variable ioption */
  ;
  capi_ioption_intent |= F2PY_INTENT_IN;
  capi_ioption_tmp = array_from_pyobj(NPY_INT,ioption_Dims,ioption_Rank,capi_ioption_intent,ioption_capi);
  if (capi_ioption_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 19th argument `ioption' of _dpropack.dlansvd_irl to C/Fortran array" );
  } else {
    ioption = (int *)(capi_ioption_tmp->data);

  /* Processing variable p */
    f2py_success = int_from_pyobj(&p,p_capi,"_dpropack.dlansvd_irl() 7th argument (p) can't be converted to int");
  if (f2py_success) {
  /* Processing variable neig */
    f2py_success = int_from_pyobj(&neig,neig_capi,"_dpropack.dlansvd_irl() 8th argument (neig) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"_dpropack.dlansvd_irl() 5th argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable which */
  slen(which) = 1;
  f2py_success = string_from_pyobj(&which,&slen(which),"",which_capi,"string_from_pyobj failed in converting 1st argument `which' of _dpropack.dlansvd_irl to C string");
  if (f2py_success) {
  /* Processing variable maxiter */
    f2py_success = int_from_pyobj(&maxiter,maxiter_capi,"_dpropack.dlansvd_irl() 9th argument (maxiter) can't be converted to int");
  if (f2py_success) {
  /* Processing variable u */
  ;
  capi_u_intent |= F2PY_INTENT_IN;
  capi_u_tmp = array_from_pyobj(NPY_DOUBLE,u_Dims,u_Rank,capi_u_intent,u_capi);
  if (capi_u_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 11st argument `u' of _dpropack.dlansvd_irl to C/Fortran array" );
  } else {
    u = (double *)(capi_u_tmp->data);

  /* Processing variable iparm */
  ;
  capi_iparm_intent |= F2PY_INTENT_IN;
  capi_iparm_tmp = array_from_pyobj(NPY_INT,iparm_Dims,iparm_Rank,capi_iparm_intent,iparm_capi);
  if (capi_iparm_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 22nd argument `iparm' of _dpropack.dlansvd_irl to C/Fortran array" );
  } else {
    iparm = (int *)(capi_iparm_tmp->data);

  /* Processing variable bnd */
  ;
  capi_bnd_intent |= F2PY_INTENT_IN;
  capi_bnd_tmp = array_from_pyobj(NPY_DOUBLE,bnd_Dims,bnd_Rank,capi_bnd_intent,bnd_capi);
  if (capi_bnd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 13rd argument `bnd' of _dpropack.dlansvd_irl to C/Fortran array" );
  } else {
    bnd = (double *)(capi_bnd_tmp->data);

  /* Processing variable jobv */
  slen(jobv) = 1;
  f2py_success = string_from_pyobj(&jobv,&slen(jobv),"",jobv_capi,"string_from_pyobj failed in converting 3rd argument `jobv' of _dpropack.dlansvd_irl to C string");
  if (f2py_success) {
  /* Processing variable jobu */
  slen(jobu) = 1;
  f2py_success = string_from_pyobj(&jobu,&slen(jobu),"",jobu_capi,"string_from_pyobj failed in converting 2nd argument `jobu' of _dpropack.dlansvd_irl to C string");
  if (f2py_success) {
  /* Processing variable tolin */
    f2py_success = double_from_pyobj(&tolin,tolin_capi,"_dpropack.dlansvd_irl() 15th argument (tolin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable aprod */
if(F2PyCapsule_Check(aprod_capi)) {
  aprod_cptr = F2PyCapsule_AsVoidPtr(aprod_capi);
} else {
  aprod_cptr = cb_daprod_in___user__routines;
}

  aprod_nofargs_capi = cb_daprod_in___user__routines_nofargs;
  if (create_cb_arglist(aprod_capi,aprod_xa_capi,7,0,&cb_daprod_in___user__routines_nofargs,&aprod_args_capi,"failed in processing argument list for call-back aprod.")) {
    jmp_buf aprod_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `aprod`.\n");
    SWAP(aprod_capi,cb_daprod_in___user__routines_capi,PyObject);
    SWAP(aprod_args_capi,cb_daprod_in___user__routines_args_capi,PyTupleObject);
    memcpy(&aprod_jmpbuf,&cb_daprod_in___user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable m */
    f2py_success = int_from_pyobj(&m,m_capi,"_dpropack.dlansvd_irl() 4th argument (m) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iwork */
  ;
  capi_iwork_intent |= F2PY_INTENT_IN;
  capi_iwork_tmp = array_from_pyobj(NPY_INT,iwork_Dims,iwork_Rank,capi_iwork_intent,iwork_capi);
  if (capi_iwork_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 17th argument `iwork' of _dpropack.dlansvd_irl to C/Fortran array" );
  } else {
    iwork = (int *)(capi_iwork_tmp->data);

  /* Processing variable info */
    f2py_success = int_from_pyobj(&info,info_capi,"_dpropack.dlansvd_irl() 20th argument (info) can't be converted to int");
  if (f2py_success) {
  /* Processing variable dim */
    f2py_success = int_from_pyobj(&dim,dim_capi,"_dpropack.dlansvd_irl() 6th argument (dim) can't be converted to int");
  if (f2py_success) {
  /* Processing variable work */
  ;
  capi_work_intent |= F2PY_INTENT_IN;
  capi_work_tmp = array_from_pyobj(NPY_DOUBLE,work_Dims,work_Rank,capi_work_intent,work_capi);
  if (capi_work_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 16th argument `work' of _dpropack.dlansvd_irl to C/Fortran array" );
  } else {
    work = (double *)(capi_work_tmp->data);

  /* Processing variable dparm */
  ;
  capi_dparm_intent |= F2PY_INTENT_IN;
  capi_dparm_tmp = array_from_pyobj(NPY_DOUBLE,dparm_Dims,dparm_Rank,capi_dparm_intent,dparm_capi);
  if (capi_dparm_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 21st argument `dparm' of _dpropack.dlansvd_irl to C/Fortran array" );
  } else {
    dparm = (double *)(capi_dparm_tmp->data);

  /* Processing variable doption */
  ;
  capi_doption_intent |= F2PY_INTENT_IN;
  capi_doption_tmp = array_from_pyobj(NPY_DOUBLE,doption_Dims,doption_Rank,capi_doption_intent,doption_capi);
  if (capi_doption_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 18th argument `doption' of _dpropack.dlansvd_irl to C/Fortran array" );
  } else {
    doption = (double *)(capi_doption_tmp->data);

  /* Processing variable sigma */
  ;
  capi_sigma_intent |= F2PY_INTENT_IN;
  capi_sigma_tmp = array_from_pyobj(NPY_DOUBLE,sigma_Dims,sigma_Rank,capi_sigma_intent,sigma_capi);
  if (capi_sigma_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_dpropack_error,"failed in converting 12nd argument `sigma' of _dpropack.dlansvd_irl to C/Fortran array" );
  } else {
    sigma = (double *)(capi_sigma_tmp->data);

  /* Processing variable ldv */
  if (ldv_capi == Py_None) ldv = shape(v,0); else
    f2py_success = int_from_pyobj(&ldv,ldv_capi,"_dpropack.dlansvd_irl() 2nd keyword (ldv) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(v,0)==ldv,"shape(v,0)==ldv","2nd keyword ldv","dlansvd_irl:ldv=%d",ldv) {
  /* Processing variable ldu */
  if (ldu_capi == Py_None) ldu = shape(u,0); else
    f2py_success = int_from_pyobj(&ldu,ldu_capi,"_dpropack.dlansvd_irl() 1st keyword (ldu) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u,0)==ldu,"shape(u,0)==ldu","1st keyword ldu","dlansvd_irl:ldu=%d",ldu) {
  /* Processing variable lwork */
  if (lwork_capi == Py_None) lwork = len(work); else
    f2py_success = int_from_pyobj(&lwork,lwork_capi,"_dpropack.dlansvd_irl() 3rd keyword (lwork) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(work)>=lwork,"len(work)>=lwork","3rd keyword lwork","dlansvd_irl:lwork=%d",lwork) {
  /* Processing variable liwork */
  if (liwork_capi == Py_None) liwork = len(iwork); else
    f2py_success = int_from_pyobj(&liwork,liwork_capi,"_dpropack.dlansvd_irl() 4th keyword (liwork) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(iwork)>=liwork,"len(iwork)>=liwork","4th keyword liwork","dlansvd_irl:liwork=%d",liwork) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_daprod_in___user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(which,jobu,jobv,&m,&n,&dim,&p,&neig,&maxiter,aprod_cptr,u,&ldu,sigma,bnd,v,&ldv,&tolin,work,&lwork,iwork,&liwork,doption,ioption,&info,dparm,iparm,slen(which),slen(jobu),slen(jobv));
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(iwork)>=liwork)*/
  } /*if (f2py_success) of liwork*/
  /* End of cleaning variable liwork */
  } /*CHECKSCALAR(len(work)>=lwork)*/
  } /*if (f2py_success) of lwork*/
  /* End of cleaning variable lwork */
  } /*CHECKSCALAR(shape(u,0)==ldu)*/
  } /*if (f2py_success) of ldu*/
  /* End of cleaning variable ldu */
  } /*CHECKSCALAR(shape(v,0)==ldv)*/
  } /*if (f2py_success) of ldv*/
  /* End of cleaning variable ldv */
  if((PyObject *)capi_sigma_tmp!=sigma_capi) {
    Py_XDECREF(capi_sigma_tmp); }
  }  /*if (capi_sigma_tmp == NULL) ... else of sigma*/
  /* End of cleaning variable sigma */
  if((PyObject *)capi_doption_tmp!=doption_capi) {
    Py_XDECREF(capi_doption_tmp); }
  }  /*if (capi_doption_tmp == NULL) ... else of doption*/
  /* End of cleaning variable doption */
  if((PyObject *)capi_dparm_tmp!=dparm_capi) {
    Py_XDECREF(capi_dparm_tmp); }
  }  /*if (capi_dparm_tmp == NULL) ... else of dparm*/
  /* End of cleaning variable dparm */
  if((PyObject *)capi_work_tmp!=work_capi) {
    Py_XDECREF(capi_work_tmp); }
  }  /*if (capi_work_tmp == NULL) ... else of work*/
  /* End of cleaning variable work */
  } /*if (f2py_success) of dim*/
  /* End of cleaning variable dim */
  } /*if (f2py_success) of info*/
  /* End of cleaning variable info */
  if((PyObject *)capi_iwork_tmp!=iwork_capi) {
    Py_XDECREF(capi_iwork_tmp); }
  }  /*if (capi_iwork_tmp == NULL) ... else of iwork*/
  /* End of cleaning variable iwork */
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
    CFUNCSMESS("Restoring jmpbuf for `aprod`.\n");
    cb_daprod_in___user__routines_capi = aprod_capi;
    Py_DECREF(cb_daprod_in___user__routines_args_capi);
    cb_daprod_in___user__routines_args_capi = aprod_args_capi;
    cb_daprod_in___user__routines_nofargs = aprod_nofargs_capi;
    memcpy(&cb_daprod_in___user__routines_jmpbuf,&aprod_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable aprod */
  } /*if (f2py_success) of tolin*/
  /* End of cleaning variable tolin */
    STRINGFREE(jobu);
  }  /*if (f2py_success) of jobu*/
  /* End of cleaning variable jobu */
    STRINGFREE(jobv);
  }  /*if (f2py_success) of jobv*/
  /* End of cleaning variable jobv */
  if((PyObject *)capi_bnd_tmp!=bnd_capi) {
    Py_XDECREF(capi_bnd_tmp); }
  }  /*if (capi_bnd_tmp == NULL) ... else of bnd*/
  /* End of cleaning variable bnd */
  if((PyObject *)capi_iparm_tmp!=iparm_capi) {
    Py_XDECREF(capi_iparm_tmp); }
  }  /*if (capi_iparm_tmp == NULL) ... else of iparm*/
  /* End of cleaning variable iparm */
  if((PyObject *)capi_u_tmp!=u_capi) {
    Py_XDECREF(capi_u_tmp); }
  }  /*if (capi_u_tmp == NULL) ... else of u*/
  /* End of cleaning variable u */
  } /*if (f2py_success) of maxiter*/
  /* End of cleaning variable maxiter */
    STRINGFREE(which);
  }  /*if (f2py_success) of which*/
  /* End of cleaning variable which */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of neig*/
  /* End of cleaning variable neig */
  } /*if (f2py_success) of p*/
  /* End of cleaning variable p */
  if((PyObject *)capi_ioption_tmp!=ioption_capi) {
    Py_XDECREF(capi_ioption_tmp); }
  }  /*if (capi_ioption_tmp == NULL) ... else of ioption*/
  /* End of cleaning variable ioption */
  if((PyObject *)capi_v_tmp!=v_capi) {
    Py_XDECREF(capi_v_tmp); }
  }  /*if (capi_v_tmp == NULL) ... else of v*/
  /* End of cleaning variable v */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of dlansvd_irl *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_timing_def[] = {
  {"nopx",0,{{-1}},NPY_INT},
  {"nreorth",0,{{-1}},NPY_INT},
  {"ndot",0,{{-1}},NPY_INT},
  {"nreorthu",0,{{-1}},NPY_INT},
  {"nreorthv",0,{{-1}},NPY_INT},
  {"nitref",0,{{-1}},NPY_INT},
  {"nrestart",0,{{-1}},NPY_INT},
  {"nbsvd",0,{{-1}},NPY_INT},
  {"tmvopx",0,{{-1}},NPY_FLOAT},
  {"tgetu0",0,{{-1}},NPY_FLOAT},
  {"tupdmu",0,{{-1}},NPY_FLOAT},
  {"tupdnu",0,{{-1}},NPY_FLOAT},
  {"tintv",0,{{-1}},NPY_FLOAT},
  {"tlanbpro",0,{{-1}},NPY_FLOAT},
  {"treorth",0,{{-1}},NPY_FLOAT},
  {"treorthu",0,{{-1}},NPY_FLOAT},
  {"treorthv",0,{{-1}},NPY_FLOAT},
  {"telru",0,{{-1}},NPY_FLOAT},
  {"telrv",0,{{-1}},NPY_FLOAT},
  {"tbsvd",0,{{-1}},NPY_FLOAT},
  {"tnorm2",0,{{-1}},NPY_FLOAT},
  {"tlansvd",0,{{-1}},NPY_FLOAT},
  {"nlandim",0,{{-1}},NPY_INT},
  {"tritzvec",0,{{-1}},NPY_FLOAT},
  {"trestart",0,{{-1}},NPY_FLOAT},
  {"tdot",0,{{-1}},NPY_FLOAT},
  {"nsing",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_timing(char *nopx,char *nreorth,char *ndot,char *nreorthu,char *nreorthv,char *nitref,char *nrestart,char *nbsvd,char *tmvopx,char *tgetu0,char *tupdmu,char *tupdnu,char *tintv,char *tlanbpro,char *treorth,char *treorthu,char *treorthv,char *telru,char *telrv,char *tbsvd,char *tnorm2,char *tlansvd,char *nlandim,char *tritzvec,char *trestart,char *tdot,char *nsing) {
  int i_f2py=0;
  f2py_timing_def[i_f2py++].data = nopx;
  f2py_timing_def[i_f2py++].data = nreorth;
  f2py_timing_def[i_f2py++].data = ndot;
  f2py_timing_def[i_f2py++].data = nreorthu;
  f2py_timing_def[i_f2py++].data = nreorthv;
  f2py_timing_def[i_f2py++].data = nitref;
  f2py_timing_def[i_f2py++].data = nrestart;
  f2py_timing_def[i_f2py++].data = nbsvd;
  f2py_timing_def[i_f2py++].data = tmvopx;
  f2py_timing_def[i_f2py++].data = tgetu0;
  f2py_timing_def[i_f2py++].data = tupdmu;
  f2py_timing_def[i_f2py++].data = tupdnu;
  f2py_timing_def[i_f2py++].data = tintv;
  f2py_timing_def[i_f2py++].data = tlanbpro;
  f2py_timing_def[i_f2py++].data = treorth;
  f2py_timing_def[i_f2py++].data = treorthu;
  f2py_timing_def[i_f2py++].data = treorthv;
  f2py_timing_def[i_f2py++].data = telru;
  f2py_timing_def[i_f2py++].data = telrv;
  f2py_timing_def[i_f2py++].data = tbsvd;
  f2py_timing_def[i_f2py++].data = tnorm2;
  f2py_timing_def[i_f2py++].data = tlansvd;
  f2py_timing_def[i_f2py++].data = nlandim;
  f2py_timing_def[i_f2py++].data = tritzvec;
  f2py_timing_def[i_f2py++].data = trestart;
  f2py_timing_def[i_f2py++].data = tdot;
  f2py_timing_def[i_f2py++].data = nsing;
}
extern void F_FUNC(f2pyinittiming,F2PYINITTIMING)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_timing(void) {
  F_FUNC(f2pyinittiming,F2PYINITTIMING)(f2py_setup_timing);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"dlansvd",-1,{{-1}},0,(char *)F_FUNC(dlansvd,DLANSVD),(f2py_init_func)f2py_rout__dpropack_dlansvd,doc_f2py_rout__dpropack_dlansvd},
  {"dlansvd_irl",-1,{{-1}},0,(char *)F_FUNC_US(dlansvd_irl,DLANSVD_IRL),(f2py_init_func)f2py_rout__dpropack_dlansvd_irl,doc_f2py_rout__dpropack_dlansvd_irl},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_dpropack",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit__dpropack(void) {
#else
#define RETVAL
PyMODINIT_FUNC init_dpropack(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = _dpropack_module = PyModule_Create(&moduledef);
#else
  m = _dpropack_module = Py_InitModule("_dpropack", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _dpropack (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module '_dpropack' is auto-generated with f2py (version:2).\nFunctions:\n"
"  u,sigma,bnd,v,work,iwork,info = dlansvd(jobu,jobv,m,n,k,aprod,u,v,tolin,work,iwork,doption,ioption,dparm,iparm,kmax=(shape(u,1)-1),ldu=shape(u,0),ldv=shape(v,0),lwork=len(work),liwork=len(iwork),aprod_extra_args=())\n"
"  dlansvd_irl(which,jobu,jobv,m,n,dim,p,neig,maxiter,aprod,u,sigma,bnd,v,tolin,work,iwork,doption,ioption,info,dparm,iparm,ldu=shape(u,0),ldv=shape(v,0),lwork=len(work),liwork=len(iwork),aprod_extra_args=())\n"
"COMMON blocks:\n""  /timing/ nopx,nreorth,ndot,nreorthu,nreorthv,nitref,nrestart,nbsvd,tmvopx,tgetu0,tupdmu,tupdnu,tintv,tlanbpro,treorth,treorthu,treorthv,telru,telrv,tbsvd,tnorm2,tlansvd,nlandim,tritzvec,trestart,tdot,nsing\n"".");
  PyDict_SetItemString(d, "__doc__", s);
  _dpropack_error = PyErr_NewException ("_dpropack.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  F2PyDict_SetItemString(d, "timing", PyFortranObject_New(f2py_timing_def,f2py_init_timing));
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_dpropack");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
